apiVersion: v1
kind: ReplicationController
metadata:
  name: express-start
spec:
  replicas: 10
  selector:
    app: express-start
  template:
    metadata:
      name: express-start
      labels:
        app: express-start
    spec:
      containers:
        - name: express-start
          image: express-start:1.0
          ports:
            - containerPort: 4000
