apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-chatroom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-chatroom
  template:
    metadata:
      labels:
        app: mini-chatroom
    spec:
      containers:
        - name: mini-chatroom
          image: mini-chatroom:0.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: mini-chatroom
spec:
  selector:
    app: mini-chatroom
  type: NodePort
  ports:
    - port: 4000
      nodePort: 30000
      targetPort: 4000

---
# apiVersion: configuration.konghq.com/v1
# kind: KongIngress
# metadata:
#   name: common-kong-ingress
# proxy:
#   path: /
#   protocol: https
# route:
#   strip_path: false
#   preserve_host: false
#   methods:
#     - POST
#     - GET
#     - PUT
#     - PATCH
#     - DELETE
#     - OPTIONS
#     - HEAD
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: joke-service
#   annotations:
#     konghq.com/override: common-kong-ingress
#     configuration.konghq.com: common-kong-ingress
# spec:
#   ports:
#     - protocol: TCP
#       port: 443
#       targetPort: 443
#   type: ExternalName
#   externalName: 47.100.122.205
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: mini-chatroom-ingress
#   annotations:
#     konghq.com/override: common-kong-ingress
#     kubernetes.io/ingress.class: kong
# spec:
#   rules:
#     - host: lb.learn.com1
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: mini-chatroom
#               servicePort: 4000
#           - path: /getJoke
#             backend:
#               serviceName: joke-service
#               servicePort: 443
