apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kong
  name: express-start
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-start
  template:
    metadata:
      labels:
        app: express-start
    spec:
      containers:
        - name: express-start
          image: express-start:1.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  namespace: kong
  name: express-start
spec:
  selector:
    app: express-start
  type: NodePort
  ports:
    - port: 4001
      nodePort: 30001
      targetPort: 4000
